# source: https://sunoprompt.com/blog/metatags-for-suno-ai-model-collection
# Bark tags
bark_tags = {
    "[announcer]": "Used to indicate a section where an announcer is speaking.",
    "[applause]": "Indicates the presence of applause in the background.",
    "[audience laughing]": "Signals that the audience is laughing, useful for live performances or shows.",
    "[barking]": "Use this tag when you want to include the sound of a dog barking.",
    "[beeping]": "To add a beeping sound, like an alarm or notification.",
    "[bell dings]": "Signifies the sound of a bell dinging.",
    "[birds chirping]": "To incorporate the ambiance of birds chirping.",
    "[bleep]": "Indicates a bleep sound, often used to censor words.",
    "[boy]": "Use this tag to specify content delivered by or related to a boy.",
    "[censored]": "Marks content that is censored.",
    "[cheering]": "To include the sound of a crowd cheering.",
    "[cheers and applause]": "Indicates both cheers and applause from an audience.",
    "[chuckles]": "Signifies chuckling sound.",
    "[clapping]": "To add the sound of clapping.",
    "[clears throat]": "Used when someone is clearing their throat.",
    "[cough]": "Indicates a coughing sound.",
    "[female narrator]": "Specifies content narrated by a female.",
    "[female]": "Use this tag for content delivered by or related to a female.",
    "[fighting]": "To include sounds or references to fighting.",
    "[giggles]": "Signifies giggling sounds.",
    "[giggling]": "Another tag for giggling sounds, perhaps in a different context or intensity.",
    "[girl]": "Use this tag to specify content delivered by or related to a girl.",
    "[groaning]": "To add a groaning sound.",
    "[man]": "Use this tag for content delivered by or related to a man.",
    "[phone ringing]": "Indicates the sound of a phone ringing.",
    "[reporter]": "Specifies content delivered by a reporter.",
    "[ringing]": "To add a generic ringing sound.",
    "[screams]": "Signifies screaming sounds.",
    "[sighs]": "Used to include a sighing sound.",
    "[silence]": "Indicates a moment of silence.",
    "[squawking]": "To add the sound of squawking, like a bird or an alarm.",
    "[upbeat music]": "Use this tag to indicate a section with upbeat music.",
    "[whispers]": "Signifies whispering sounds.",
    "[whistling]": "To include a whistling sound.",
    "[woman]": "Use this tag for content delivered by or related to a woman.",
}

# Chirp tags
chirp_tags = {
    "[Chorus]": "Indicates the part of the song meant to be the chorus.",
    "[Intro]": "Marks the introduction section of a track.",
    "[Outro]": "Signifies the outro or closing section of the music piece.",
    "[Verse]": "Used to denote the verse part of a song.",
    "[Acoustic]": "Points to an acoustic style of music.",
    "[African]": "Tags the music with African influences or origins.",
    "[Alternative metal]": "Identifies the song as belonging to the alternative metal genre.",
    "[Alternative pop]": "Marks the song as alternative pop in style.",
    "[Ambient]": "For music that has an ambient, atmospheric feel.",
    "[Atlanta rap]": "Denotes rap music that originates from or is styled after Atlanta's rap scene.",
    "[Ballad]": "Marks the piece as a ballad, often slow and emotive.",
    "[Baroque]": "Indicates music influenced by or made in the Baroque style.",
    "[Blues]": "Tags the music as belonging to the blues genre.",
    "[Boom bap]": "Signifies a style of hip-hop that includes hard-hitting beats, often known as Boom bap.",
    "[Cello]": "For pieces that feature the cello.",
    "[Chill]": "Tags music that has a relaxed, chill vibe.",
    "[Christian & Gospel]": "Indicates the music belongs to the Christian & Gospel genres.",
    "[Christmas]": "For music that fits the Christmas holiday theme.",
    "[Country & Americana]": "Marks the music as part of the country or Americana genres.",
    "[Dance & Electronic]": "For music that falls under dance or electronic categories.",
    "[Drums]": "Indicates a focus on or significant use of drums.",
    "[EDM]": "Tags the track as Electronic Dance Music.",
    "[Girl group]": "To denote music by or in the style of a girl group.",
    "[Gospel]": "Marks the piece as gospel music.",
    "[Hardcore rap]": "Indicates a hardcore rap style.",
    "[Heavy metal]": "For music in the heavy metal genre.",
    "[Hip hop]": "Tags the music as hip hop.",
    "[Indie]": "For music that is considered independent or indie in style.",
    "[Indie rock]": "Marks the track as indie rock.",
    "[J-pop]": "For music in the Japanese pop genre.",
    "[Jazz]": "Indicates jazz music.",
    "[K-pop]": "For Korean pop music.",
    "[Lo-fi]": "Tags the music with a lo-fi, understated quality.",
    "[Orchestra]": "Denotes an orchestral music style.",
    "[Party]": "For tracks that set a party mood or vibe.",
    "[Piano]": "Indicates significant use of the piano.",
    "[Pop]": "Tags the track as pop music.",
    "[Pop-Rock]": "For music that blends elements of pop and rock.",
    "[Post-Hardcore]": "Indicates a post-hardcore style in music.",
    "[Punk Rock]": "For music belonging to the punk rock genre.",
    "[R&B]": "Marks the piece as rhythm and blues.",
    "[R&B & Soul]": "Indicates a mix of R&B and soul music.",
    "[Rap]": "Tags the track as rap music.",
    "[Reggae]": "For music with reggae elements.",
    "[Rock]": "Indicates rock music.",
    "[Romantic]": "For music with a romantic theme or tone.",
    "[Soul]": "Marks the track as soul music.",
    "[Synth]": "Denotes a significant use of synthesizers.",
    "[Synth pop]": "For music in the synth-pop style.",
    "[Techno]": "Tags the music as techno.",
    "[Uk]": "Could indicate music from or influenced by the United Kingdom.",
}